using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// One narrative dialog, generated by Tools > TimeDesk > Generate World from
/// world_source.json "dialogs" (never edited by hand). Offered in the
/// interview hub on a day when its conditions pass on the day-start snapshot,
/// its structure is sound and, if one-shot, it is not done yet (InterviewDay).
/// </summary>
public sealed class DialogSO : ScriptableObject
{
    /// <summary>The dialog: its hub label, nodes, lines and choices, with stable ids.</summary>
    public AuthoredDialog dialog = new();

    /// <summary>When it is offered (the authored conditions).</summary>
    public List<TriggerCondition> conditions = new();
}
