using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// One interview question, generated by Tools > TimeDesk > Generate World from
/// world_source.json "questions" (never edited by hand). Askable on a day when
/// all its conditions pass on the day-start snapshot (InterviewDay).
/// </summary>
public sealed class QuestionSO : ScriptableObject
{
    /// <summary>The question: its category, ask-menu label and wording, with stable line ids.</summary>
    public InterviewQuestion question = new();

    /// <summary>When it is askable: DayAtLeast fromDay (when fromDay &gt; 1) plus the authored conditions.</summary>
    public List<TriggerCondition> conditions = new();
}
