// Generated by HallFloorShadowGeometry. Source 2172x724, horizon (1090,300).
static const float4 HallBoxMin[30]={float4(-6.447514,0,16.57458,0),float4(-1.287356,0,10.90909,0),float4(-4.678899,0,25.21008,0),float4(2.256881,0,25.21008,0),float4(-6.193548,0,15.95745,0),float4(-2.27027,0,10.10101,0),float4(-1.373494,0,9.009009,0),float4(0.9849397,0,9.009009,0),float4(2.128378,0,10.10101,0),float4(-5.771186,0,25.21008,0),float4(-4.430769,0,22.90076,0),float4(-1.823077,0,22.90076,0),float4(-1.118644,0,25.21008,0),float4(1.067797,0,25.21008,0),float4(1.638462,0,22.90076,0),float4(4.176923,0,22.90076,0),float4(5.389831,0,25.21008,0),float4(-8.056266,0,7.614213,0),float4(-7.043478,0,7.614213,0),float4(-6.084399,0,7.614213,0),float4(-5.094629,0,7.614213,0),float4(-4.143222,0,7.614213,0),float4(-3.168798,0,7.614213,0),float4(-2.063939,0,7.614213,0),float4(-1.150895,0,7.614213,0),float4(-0.03836317,0,7.614213,0),float4(0.943734,0,7.614213,0),float4(2.079284,0,7.614213,0),float4(3.092072,0,7.614213,0),float4(4.219949,0,7.614213,0)};
static const float4 HallBoxMax[30]={float4(-6.060402,2.836364,20.13423,0.23),float4(1.2,0.369403,11.49425,0.19),float4(-2.218488,0.4473684,27.52294,0.17),float4(4.134454,0.4473684,27.52294,0.17),float4(-5.776596,0.5454546,16.12903,0.18),float4(-2.20202,1.057336,10.13513,0.19),float4(-1.315315,0.9428571,9.036144,0.19),float4(1.036036,0.9428571,9.036144,0.19),float4(2.181818,1.057336,10.13513,0.19),float4(-5.571429,1.278481,25.42373,0.19),float4(-4.259542,1.16092,23.07692,0.19),float4(-1.671756,1.16092,23.07692,0.19),float4(-0.9579833,1.278481,25.42373,0.19),float4(1.210084,1.278481,25.42373,0.19),float4(1.763359,1.16092,23.07692,0.19),float4(4.282443,1.16092,23.07692,0.19),float4(5.495799,1.278481,25.42373,0.19),float4(-7.949238,1.089172,7.672634,0.2),float4(-6.944162,1.089172,7.672634,0.2),float4(-5.992385,1.089172,7.672634,0.2),float4(-5.010152,1.089172,7.672634,0.2),float4(-4.06599,1.089172,7.672634,0.2),float4(-3.098985,1.089172,7.672634,0.2),float4(-2.002538,1.089172,7.672634,0.2),float4(-1.096447,1.089172,7.672634,0.2),float4(0.00761421,1.089172,7.672634,0.2),float4(0.9822335,1.089172,7.672634,0.2),float4(2.109137,1.089172,7.672634,0.2),float4(3.114213,1.089172,7.672634,0.2),float4(4.233502,1.089172,7.672634,0.2)};
static const float4 HallRingPosition[3]={float4(0.02222222,11.11111,1.011111,0.14),float4(-3.284483,25.86207,1.318965,0.14),float4(3.232759,25.86207,1.318965,0.14)};
static const float4 HallRingSize[3]={float4(0.8444444,0.7777777,0.26,0),float4(1.112069,0.9310344,0.26,0),float4(1.112069,0.9310344,0.26,0)};

float4 _HallShadowRay;
float HallSlab(float p,float d,float lo,float hi,inout float enter,inout float leave)
{
 if(abs(d)<.00001)return step(lo,p)*step(p,hi);
 float2 t=float2(lo-p,hi-p)/d;enter=max(enter,min(t.x,t.y));leave=min(leave,max(t.x,t.y));return step(enter,leave);
}
float HallGeometricShadow(float2 pixel,float4 weights)
{
 if(pixel.y<=301)return 0;
 float day=weights.x+weights.y+weights.z;if(day<.0001)return 0;
 // Interpolate light direction first: the silhouettes move continuously rather than double-exposing three static masks.
 float2 slope=_HallShadowRay.xy;
 // Avoid a degenerate exactly edge-on ring for a single intermediate frame.
 slope.y=abs(slope.y)<.005?(slope.y<0?-.005:.005):slope.y;
 float depth=3000/(pixel.y-300);float2 p=float2((pixel.x-1090)*depth/1000,depth);float shade=0;
[loop] for(int i=0;i<30;i++){

 float4 a=HallBoxMin[i],b=HallBoxMax[i];float enter=0,leave=b.y;float penumbra=.025*b.y;
 float hit=HallSlab(p.x,-slope.x,a.x-penumbra,b.x+penumbra,enter,leave);
 hit*=HallSlab(p.y,-slope.y,a.z-penumbra,b.z+penumbra,enter,leave);
 shade=max(shade,hit*smoothstep(0,.06+penumbra,max(0,leave-enter))*b.w);
 }
 [unroll] for(int j=0;j<3;j++){
 float4 r=HallRingPosition[j],size=HallRingSize[j];float h=(p.y-r.y)/slope.y;
 float radius=length(float2((p.x-slope.x*h-r.x)/size.x,(h-r.z)/size.y));
 float soft=.025+.014*max(0,h);float hit=(1-smoothstep(r.w,r.w+soft,abs(radius-1)))*step(.0001,h);
 shade=max(shade,hit*size.z);
 }
 return shade*day;
}
