// ReSharper disable InconsistentNaming
using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Central content registry (data only).
/// You create one ContentLibrary asset and assign all your DayPlans, Eras, Clues, etc.
/// Runtime systems query this instead of hardcoding references.
/// </summary>
[CreateAssetMenu(fileName = "ContentLibrary_", menuName = "TimeDesk/Content Library", order = 0)]
public sealed class ContentLibrarySO : ScriptableObject
{
    /// <summary>All day plans (D1..D7..etc).</summary>
    [SerializeField] private DayPlanSO[] dayPlans;

    /// <summary>All eras available in the game.</summary>
    [SerializeField] private EraSO[] eras;

    /// <summary>All clues that can appear in documents.</summary>
    [SerializeField] private ClueSO[] clues;

    /// <summary>All premade characters (generated by Generate World from world_source.json "premades").</summary>
    [SerializeField] private LegendarySO[] legendaries;

    /// <summary>Optional: effects list for lookups/UI.</summary>
    [SerializeField] private EffectSO[] effects;

    /// <summary>Optional: upgrades list for lookups.</summary>
    [SerializeField] private UpgradeSO[] upgrades;

    [Header("Timeline Variation")]
    /// <summary>All key attributes (cultures/traits) tracked by the timeline.</summary>
    [SerializeField] private AttributeSO[] attributes;

    /// <summary>All nations.</summary>
    [SerializeField] private NationSO[] nations;

    /// <summary>All nation-era profiles (nation at a time period).</summary>
    [SerializeField] private NationEraProfileSO[] nationEraProfiles;

    /// <summary>All visitor archetypes.</summary>
    [SerializeField] private ArchetypeSO[] archetypes;

    /// <summary>All timeline triggers (special conditions).</summary>
    [SerializeField] private TimelineTriggerSO[] timelineTriggers;

    [Header("Home (Phase 4)")]
    /// <summary>All slot machine outcomes available at Home.</summary>
    [SerializeField] private SlotOutcomeSO[] slotOutcomes;

    [Header("Endings (Phase 5)")]
    /// <summary>All possible run endings (fired, bankrupt, score/day thresholds).</summary>
    [SerializeField] private EndingSO[] endings;

    [Header("Investigation")]
    /// <summary>Reference books the player consults (one per clue category).</summary>
    [SerializeField] private ReferenceBookSO[] referenceBooks;

    [Header("Interview")]
    /// <summary>The interview's fixed wording and layout limits (written by Generate World from world_source.json "interview").</summary>
    [SerializeField] private InterviewLines interview = new();

    /// <summary>Interview questions, in ask-menu order (generated from world_source.json "questions").</summary>
    [SerializeField] private QuestionSO[] questions;

    /// <summary>Narrative dialogs (generated from world_source.json "dialogs").</summary>
    [SerializeField] private DialogSO[] dialogs;

    [Header("Characters")]
    /// <summary>Face bands, grey age, the premade garment label and confusable pairs (written by Generate World from world_source.json "looks").</summary>
    [SerializeField] private LookRules lookRules = new();

    /// <summary>The look knobs every traveller shares.</summary>
    public LookRules LookRules => lookRules;

    /// <summary>Public read-only access to reference books.</summary>
    public IReadOnlyList<ReferenceBookSO> ReferenceBooks => referenceBooks ?? System.Array.Empty<ReferenceBookSO>();

    /// <summary>
    /// Today's places: profiles whose era the plan includes and whose nation it
    /// allows, ordered by country (library nation order) then era (chronological).
    /// Places missing a nation/era (or their ids) are skipped with a warning
    /// (the validator reports them as errors).
    /// </summary>
    public List<NationEraProfileSO> TodaysProfiles(DayPlanSO plan)
    {
        var result = new List<NationEraProfileSO>();

        if (nationEraProfiles == null || plan == null)
            return result;

        foreach (NationEraProfileSO p in nationEraProfiles)
        {
            if (p == null)
                continue;

            if (p.nation == null || p.era == null || string.IsNullOrWhiteSpace(p.nation.id) || string.IsNullOrWhiteSpace(p.era.id))
            {
                Debug.LogWarning($"[ContentLibrarySO] Place '{p.name}' has no nation/era id; it is left out of today's world (Tools > TimeDesk > Validate Content Library).", p);
                continue;
            }

            if (!plan.IncludesEra(p.era) || !plan.AllowsNation(p.nation))
                continue;

            result.Add(p);
        }

        result.Sort((a, b) =>
        {
            int byNation = NationOrder(a.nation).CompareTo(NationOrder(b.nation));
            return byNation != 0 ? byNation : a.era.order.CompareTo(b.era.order);
        });
        return result;
    }

    /// <summary>
    /// The day's fact snapshot: every fact of today's places, in book order.
    /// The only code that turns place data into facts, so the reference books
    /// and the papers read the same values (and history-dependent facts have
    /// one place to plug in).
    /// </summary>
    public FactTable BuildFactTable(DayPlanSO plan)
    {
        var table = new FactTable();

        foreach (NationEraProfileSO p in TodaysProfiles(plan))
        {
            if (p.facts == null)
                continue;

            foreach (ProfileFact f in p.facts)
                if (f != null)
                    table.Add(p.nation.id, p.era.id, p.OriginLabel, f.category, f.value);
        }

        return table;
    }

    /// <summary>Categories that have a reference book (only these can carry a place-fact tell, on papers or in an answer).</summary>
    public HashSet<ClueCategory> ReferenceBookCategories()
    {
        var categories = new HashSet<ClueCategory>();
        foreach (ReferenceBookSO book in ReferenceBooks)
            if (book != null)
                categories.Add(book.category);
        return categories;
    }

    /// <summary>Position of a nation in the library (unlisted nations sort last).</summary>
    private int NationOrder(NationSO nation)
    {
        int i = nations != null ? Array.IndexOf(nations, nation) : -1;
        return i < 0 ? int.MaxValue : i;
    }

    /// <summary>Public read-only access to day plans.</summary>
    public IReadOnlyList<DayPlanSO> DayPlans => dayPlans ?? System.Array.Empty<DayPlanSO>();

    /// <summary>Public read-only access to eras.</summary>
    public IReadOnlyList<EraSO> Eras => eras;

    /// <summary>Public read-only access to clues.</summary>
    public IReadOnlyList<ClueSO> Clues => clues;

    /// <summary>Public read-only access to the premade characters.</summary>
    public IReadOnlyList<LegendarySO> Legendaries => legendaries ?? System.Array.Empty<LegendarySO>();

    /// <summary>Public read-only access to effects.</summary>
    public IReadOnlyList<EffectSO> Effects => effects ?? System.Array.Empty<EffectSO>();

    /// <summary>Public read-only access to upgrades (Home shop).</summary>
    public IReadOnlyList<UpgradeSO> Upgrades => upgrades ?? System.Array.Empty<UpgradeSO>();

    /// <summary>Public read-only access to slot machine outcomes (Home).</summary>
    public IReadOnlyList<SlotOutcomeSO> SlotOutcomes => slotOutcomes ?? System.Array.Empty<SlotOutcomeSO>();

    /// <summary>Public read-only access to endings.</summary>
    public IReadOnlyList<EndingSO> Endings => endings ?? System.Array.Empty<EndingSO>();

    /// <summary>Public read-only access to attributes.</summary>
    public IReadOnlyList<AttributeSO> Attributes => attributes ?? System.Array.Empty<AttributeSO>();

    /// <summary>Public read-only access to nations.</summary>
    public IReadOnlyList<NationSO> Nations => nations ?? System.Array.Empty<NationSO>();

    /// <summary>Public read-only access to nation-era profiles.</summary>
    public IReadOnlyList<NationEraProfileSO> Profiles => nationEraProfiles ?? System.Array.Empty<NationEraProfileSO>();

    /// <summary>Public read-only access to archetypes.</summary>
    public IReadOnlyList<ArchetypeSO> Archetypes => archetypes ?? System.Array.Empty<ArchetypeSO>();

    /// <summary>Public read-only access to timeline triggers.</summary>
    public IReadOnlyList<TimelineTriggerSO> Triggers => timelineTriggers ?? System.Array.Empty<TimelineTriggerSO>();

    /// <summary>The interview's fixed wording and layout limits.</summary>
    public InterviewLines Interview => interview;

    /// <summary>Public read-only access to interview questions (ask-menu order).</summary>
    public IReadOnlyList<QuestionSO> Questions => questions ?? System.Array.Empty<QuestionSO>();

    /// <summary>Public read-only access to narrative dialogs.</summary>
    public IReadOnlyList<DialogSO> Dialogs => dialogs ?? System.Array.Empty<DialogSO>();

    /// <summary>
    /// Finds the authored profile for a nation at an era (null if none authored).
    /// </summary>
    public NationEraProfileSO GetProfile(NationSO nation, EraSO era)
    {
        if (nation == null || era == null || nationEraProfiles == null)
            return null;

        foreach (NationEraProfileSO p in nationEraProfiles)
            if (p != null && p.nation == nation && p.era == era)
                return p;

        return null;
    }

    /// <summary>Cached lookup: era id -> era asset.</summary>
    private Dictionary<string, EraSO> _eraById;

    /// <summary>Cached lookup: effect asset name -> effect asset.</summary>
    private Dictionary<string, EffectSO> _effectByName;

    /// <summary>Cached lookup: upgrade id -> upgrade asset.</summary>
    private Dictionary<string, UpgradeSO> _upgradeById;

    /// <summary>Cached lookup: ending id -> ending asset.</summary>
    private Dictionary<string, EndingSO> _endingById;

    /// <summary>
    /// Clears cached lookups when the asset is loaded/reloaded.
    /// This prevents stale dictionaries after domain reloads or inspector edits.
    /// </summary>
    private void OnEnable()
    {
        _eraById = null;
        _effectByName = null;
        _upgradeById = null;
        _endingById = null;
    }

    /// <summary>
    /// Returns an Era by its string ID (e.g., "rome").
    /// Useful for saves or ID-based references.
    /// </summary>
    public EraSO GetEraById(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return null;

        EnsureLookups();
        return _eraById.TryGetValue(id, out EraSO era) ? era : null;
    }

    /// <summary>
    /// Returns an Upgrade by its string ID (e.g., "scanner").
    /// Used when loading save data that stores upgrade IDs.
    /// </summary>
    public UpgradeSO GetUpgradeById(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return null;

        EnsureLookups();
        return _upgradeById.TryGetValue(id, out UpgradeSO upgrade) ? upgrade : null;
    }

    /// <summary>
    /// Returns an Ending by its string ID (e.g., "fired", "bankrupt").
    /// Used by the title scene to display WorldState.endingId.
    /// </summary>
    public EndingSO GetEndingById(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return null;

        EnsureLookups();
        return _endingById.TryGetValue(id, out EndingSO ending) ? ending : null;
    }

    /// <summary>
    /// Returns an Effect by its asset name (effect.name).
    /// If you later add a stable id field to EffectSO, switch to that.
    /// </summary>
    public EffectSO GetEffectByAssetName(string assetName)
    {
        if (string.IsNullOrWhiteSpace(assetName))
            return null;

        EnsureLookups();
        return _effectByName.TryGetValue(assetName, out EffectSO effect) ? effect : null;
    }

    /// <summary>
    /// Finds the DayPlan matching a given dayNumber.
    /// Keeps day progression data-driven (D1..D7...).
    /// </summary>
    public DayPlanSO GetDayPlan(int dayNumber)
    {
        if (dayPlans == null)
            return null;

        foreach (DayPlanSO plan in dayPlans)
        {
            if (plan != null && plan.DayNumber == dayNumber)
                return plan;
        }

        return null;
    }

    /// <summary>
    /// Builds internal dictionaries the first time they are needed.
    /// </summary>
    private void EnsureLookups()
    {
        if (_eraById != null)
            return;

        _eraById = new Dictionary<string, EraSO>(StringComparer.OrdinalIgnoreCase);
        _effectByName = new Dictionary<string, EffectSO>(StringComparer.OrdinalIgnoreCase);
        _upgradeById = new Dictionary<string, UpgradeSO>(StringComparer.OrdinalIgnoreCase);
        _endingById = new Dictionary<string, EndingSO>(StringComparer.OrdinalIgnoreCase);

        if (eras != null)
        {
            foreach (EraSO e in eras)
            {
                if (e == null || string.IsNullOrWhiteSpace(e.id))
                    continue;

                _eraById.TryAdd(e.id, e);
            }
        }

        if (effects != null)
        {
            foreach (EffectSO fx in effects)
            {
                if (fx == null)
                    continue;

                _effectByName.TryAdd(fx.name, fx);
            }
        }

        if (upgrades != null)
        {
            foreach (UpgradeSO u in upgrades)
            {
                if (u == null || string.IsNullOrWhiteSpace(u.id))
                    continue;

                _upgradeById.TryAdd(u.id, u);
            }
        }

        if (endings != null)
        {
            foreach (EndingSO e in endings)
            {
                if (e == null || string.IsNullOrWhiteSpace(e.id))
                    continue;

                _endingById.TryAdd(e.id, e);
            }
        }
    }
}
