// ReSharper disable InconsistentNaming
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

/// <summary>
/// Central content registry (data only).
/// You create one ContentLibrary asset and assign all your DayPlans, Eras, Clues, etc.
/// Runtime systems query this instead of hardcoding references.
/// </summary>
[CreateAssetMenu(fileName = "ContentLibrary_", menuName = "TimeDesk/Content Library", order = 0)]
public sealed class ContentLibrarySO : ScriptableObject
{
    /// <summary>All day plans (D1..D7..etc).</summary>
    [SerializeField] private DayPlanSO[] dayPlans;

    /// <summary>All eras available in the game.</summary>
    [SerializeField] private EraSO[] eras;

    /// <summary>All clues that can appear in documents.</summary>
    [SerializeField] private ClueSO[] clues;

    /// <summary>All premade characters (generated by Generate World from world_source.json "premades").</summary>
    [SerializeField] private LegendarySO[] legendaries;

    /// <summary>Optional: effects list for lookups/UI.</summary>
    [SerializeField] private EffectSO[] effects;

    /// <summary>Optional: upgrades list for lookups.</summary>
    [SerializeField] private UpgradeSO[] upgrades;

    [Header("Timeline Variation")]
    /// <summary>All key attributes (cultures/traits) tracked by the timeline.</summary>
    [SerializeField] private AttributeSO[] attributes;

    /// <summary>All nations.</summary>
    [SerializeField] private NationSO[] nations;

    /// <summary>All nation-era profiles (nation at a time period).</summary>
    [SerializeField] private NationEraProfileSO[] nationEraProfiles;

    /// <summary>All visitor archetypes.</summary>
    [SerializeField] private ArchetypeSO[] archetypes;

    /// <summary>All timeline triggers (special conditions).</summary>
    [SerializeField] private TimelineTriggerSO[] timelineTriggers;

    [Header("Home (Phase 4)")]
    /// <summary>All slot machine outcomes available at Home.</summary>
    [SerializeField] private SlotOutcomeSO[] slotOutcomes;

    [Header("Endings (Phase 5)")]
    /// <summary>All possible run endings (fired, bankrupt, score/day thresholds).</summary>
    [SerializeField] private EndingSO[] endings;

    [Header("Investigation")]
    /// <summary>Reference books the player consults (one per clue category).</summary>
    [SerializeField] private ReferenceBookSO[] referenceBooks;

    [Header("Interview")]
    /// <summary>The interview's fixed wording and layout limits (written by Generate World from world_source.json "interview").</summary>
    [SerializeField] private InterviewLines interview = new();

    /// <summary>Interview questions, in ask-menu order (generated from world_source.json "questions").</summary>
    [SerializeField] private QuestionSO[] questions;

    /// <summary>Narrative dialogs (generated from world_source.json "dialogs").</summary>
    [SerializeField] private DialogSO[] dialogs;

    [Header("History")]
    /// <summary>Wording of the templated history news (written by Generate World from world_source.json "history.lines").</summary>
    [SerializeField] private HistoryLines historyLines = new();

    [Header("PC")]
    /// <summary>The PC's content: the Internet's sites, the Static sites' pages and the Lineage Archive's people (written by Generate World from world_source.json "pc").</summary>
    [SerializeField] private PcContent pc = new();

    [Header("Characters")]
    /// <summary>Face bands, grey age, the premade garment label and confusable pairs (written by Generate World from world_source.json "looks").</summary>
    [SerializeField] private LookRules lookRules = new();

    /// <summary>The look knobs every traveller shares.</summary>
    public LookRules LookRules => lookRules;

    [Header("Culture (piece 6)")]
    /// <summary>The culture UI knobs (written by Generate World from world_source.json "ui").</summary>
    [SerializeField] private CultureUiSettings cultureUi = new();

    /// <summary>The PC's look before any country leads the Future (generated).</summary>
    [SerializeField] private ThemeSO neutralTheme;

    /// <summary>One theme per nation, in library nation order (generated).</summary>
    [SerializeField] private ThemeSO[] themes;

    /// <summary>The UI string tables: the reading language's and one per culture language (generated).</summary>
    [SerializeField] private UiStringTableSO[] stringTables;

    [Header("Translation (piece 9)")]
    /// <summary>The tongues, packs, scripts, flip knobs and fallback cipher (written by Generate World from world_source.json "translation").</summary>
    [SerializeField] private TranslationSettings translation = new();

    [Header("Agency (redesign phase 2)")]
    /// <summary>The agency's printed name, programme line and day 1's date (written by Generate World from world_source.json "agency").</summary>
    [SerializeField] private AgencyContent agency = new();

    /// <summary>Public read-only access to reference books.</summary>
    public IReadOnlyList<ReferenceBookSO> ReferenceBooks => referenceBooks ?? System.Array.Empty<ReferenceBookSO>();

    /// <summary>
    /// Today's places: profiles whose era the plan includes and whose nation it
    /// allows, and at most one Future place: <paramref name="futureNationId"/>'s
    /// (History.FutureNation, History.InWorld; none for null). Ordered by
    /// country (library nation order) then era (chronological). Places missing
    /// a nation/era (or their ids) are skipped with a warning (the validator
    /// reports them as errors).
    /// </summary>
    public List<NationEraProfileSO> TodaysProfiles(DayPlanSO plan, string futureNationId)
    {
        var result = new List<NationEraProfileSO>();

        if (nationEraProfiles == null || plan == null)
            return result;

        foreach (NationEraProfileSO p in nationEraProfiles)
        {
            if (p == null)
                continue;

            if (p.nation == null || p.era == null || string.IsNullOrWhiteSpace(p.nation.id) || string.IsNullOrWhiteSpace(p.era.id))
            {
                Debug.LogWarning($"[ContentLibrarySO] Place '{p.name}' has no nation/era id; it is left out of today's world (Tools > TimeDesk > Validate Content Library).", p);
                continue;
            }

            if (!plan.IncludesEra(p.era) || !plan.AllowsNation(p.nation) || !History.InWorld(p.era.isFuture, p.nation.id, futureNationId))
                continue;

            result.Add(p);
        }

        result.Sort((a, b) =>
        {
            int byNation = NationOrder(a.nation).CompareTo(NationOrder(b.nation));
            return byNation != 0 ? byNation : a.era.order.CompareTo(b.era.order);
        });
        return result;
    }

    /// <summary>
    /// Today's world, built once per day: today's places (with the Future
    /// place of the history's leader, if any) and their facts with history
    /// applied, in book order, so case generation and the reference books
    /// share one list and one table.
    /// </summary>
    public TodaysWorld BuildToday(DayPlanSO plan, HistoryState history)
    {
        List<NationEraProfileSO> places = TodaysProfiles(plan, History.FutureNation(history));
        var table = new FactTable();
        FillFacts(table, places, history);
        return new TodaysWorld(places, table);
    }

    /// <summary>
    /// Every place's facts with history applied (every profile with a nation
    /// and era id, in library order): what the night steps compare against,
    /// and the Future currency piece 6 shows in the wallet. A null history
    /// gives the authored facts.
    /// </summary>
    public FactTable BuildWorldFacts(HistoryState history)
    {
        var table = new FactTable();
        FillFacts(table, Profiles.Where(p => p != null && p.nation != null && p.era != null &&
                                             !string.IsNullOrWhiteSpace(p.nation.id) && !string.IsNullOrWhiteSpace(p.era.id)), history);
        return table;
    }

    /// <summary>
    /// The only code that turns place facts into table rows: history is
    /// resolved before Add (History.Resolve), so papers, books, tells and
    /// answers all follow it. It is also the only code that sees a fact's
    /// authored and resolved values together, so it also marks the rows history
    /// revised (History.IsRevised; the books show them, piece 6).
    /// </summary>
    private static void FillFacts(FactTable table, IEnumerable<NationEraProfileSO> places, HistoryState history)
    {
        foreach (NationEraProfileSO p in places)
        {
            if (p.facts == null)
                continue;

            foreach (ProfileFact f in p.facts)
            {
                if (f == null)
                    continue;
                table.Add(p.nation.id, p.era.id, p.OriginLabel, f.category, History.Resolve(history, p.nation.id, p.era.id, f.category, f.value));
                if (History.IsRevised(history, p.nation.id, p.era.id, f.category, f.value))
                    table.MarkChanged(p.nation.id, p.era.id, f.category);
            }
        }
    }

    /// <summary>Categories that have a reference book (only these can carry a place-fact tell, on papers or in an answer).</summary>
    public HashSet<ClueCategory> ReferenceBookCategories()
    {
        var categories = new HashSet<ClueCategory>();
        foreach (ReferenceBookSO book in ReferenceBooks)
            if (book != null)
                categories.Add(book.category);
        return categories;
    }

    /// <summary>Position of a nation in the library (unlisted nations sort last).</summary>
    private int NationOrder(NationSO nation)
    {
        int i = nations != null ? Array.IndexOf(nations, nation) : -1;
        return i < 0 ? int.MaxValue : i;
    }

    /// <summary>Public read-only access to day plans.</summary>
    public IReadOnlyList<DayPlanSO> DayPlans => dayPlans ?? System.Array.Empty<DayPlanSO>();

    /// <summary>Public read-only access to eras.</summary>
    public IReadOnlyList<EraSO> Eras => eras;

    /// <summary>Public read-only access to clues.</summary>
    public IReadOnlyList<ClueSO> Clues => clues;

    /// <summary>Public read-only access to the premade characters.</summary>
    public IReadOnlyList<LegendarySO> Legendaries => legendaries ?? System.Array.Empty<LegendarySO>();

    /// <summary>Public read-only access to effects.</summary>
    public IReadOnlyList<EffectSO> Effects => effects ?? System.Array.Empty<EffectSO>();

    /// <summary>Public read-only access to upgrades (Home shop).</summary>
    public IReadOnlyList<UpgradeSO> Upgrades => upgrades ?? System.Array.Empty<UpgradeSO>();

    /// <summary>Public read-only access to slot machine outcomes (Home).</summary>
    public IReadOnlyList<SlotOutcomeSO> SlotOutcomes => slotOutcomes ?? System.Array.Empty<SlotOutcomeSO>();

    /// <summary>Public read-only access to endings.</summary>
    public IReadOnlyList<EndingSO> Endings => endings ?? System.Array.Empty<EndingSO>();

    /// <summary>Public read-only access to attributes.</summary>
    public IReadOnlyList<AttributeSO> Attributes => attributes ?? System.Array.Empty<AttributeSO>();

    /// <summary>Public read-only access to nations.</summary>
    public IReadOnlyList<NationSO> Nations => nations ?? System.Array.Empty<NationSO>();

    /// <summary>Public read-only access to nation-era profiles.</summary>
    public IReadOnlyList<NationEraProfileSO> Profiles => nationEraProfiles ?? System.Array.Empty<NationEraProfileSO>();

    /// <summary>Public read-only access to archetypes.</summary>
    public IReadOnlyList<ArchetypeSO> Archetypes => archetypes ?? System.Array.Empty<ArchetypeSO>();

    /// <summary>Public read-only access to timeline triggers.</summary>
    public IReadOnlyList<TimelineTriggerSO> Triggers => timelineTriggers ?? System.Array.Empty<TimelineTriggerSO>();

    /// <summary>The interview's fixed wording and layout limits.</summary>
    public InterviewLines Interview => interview;

    /// <summary>Public read-only access to interview questions (ask-menu order).</summary>
    public IReadOnlyList<QuestionSO> Questions => questions ?? System.Array.Empty<QuestionSO>();

    /// <summary>Public read-only access to narrative dialogs.</summary>
    public IReadOnlyList<DialogSO> Dialogs => dialogs ?? System.Array.Empty<DialogSO>();

    /// <summary>The templated history news wording (never null).</summary>
    public HistoryLines HistoryLines => historyLines ?? new HistoryLines();

    /// <summary>The PC's content: sites, authored pages, the Lineage Archive's people (never null).</summary>
    public PcContent Pc => pc ?? new PcContent();

    /// <summary>The culture UI knobs (never null).</summary>
    public CultureUiSettings CultureUi => cultureUi ?? new CultureUiSettings();

    /// <summary>The PC's look before any country leads the Future (null until Generate World ran).</summary>
    public ThemeSO NeutralTheme => neutralTheme;

    /// <summary>The culture themes, in library nation order.</summary>
    public IReadOnlyList<ThemeSO> Themes => themes ?? System.Array.Empty<ThemeSO>();

    /// <summary>The UI string tables.</summary>
    public IReadOnlyList<UiStringTableSO> StringTables => stringTables ?? System.Array.Empty<UiStringTableSO>();

    /// <summary>What translation reads at runtime (piece 9): the rules, the scripts, the flip's knobs and the fallback cipher (empty until Generate World ran).</summary>
    public TranslationSettings Translation => translation ?? new TranslationSettings();

    /// <summary>The agency block: its name, programme line and first date (never null).</summary>
    public AgencyContent Agency => agency ?? new AgencyContent();

    /// <summary>The office's own time: the first era marked isFuture, or null when the content has none.</summary>
    public EraSO FutureEra => eras?.FirstOrDefault(e => e != null && e.isFuture);

    /// <summary>
    /// Finds the authored profile for a nation at an era (null if none authored).
    /// </summary>
    public NationEraProfileSO GetProfile(NationSO nation, EraSO era)
    {
        if (nation == null || era == null || nationEraProfiles == null)
            return null;

        foreach (NationEraProfileSO p in nationEraProfiles)
            if (p != null && p.nation == nation && p.era == era)
                return p;

        return null;
    }

    /// <summary>Cached lookup: era id -> era asset.</summary>
    private Dictionary<string, EraSO> _eraById;

    /// <summary>Cached lookup: effect asset name -> effect asset.</summary>
    private Dictionary<string, EffectSO> _effectByName;

    /// <summary>Cached lookup: upgrade id -> upgrade asset.</summary>
    private Dictionary<string, UpgradeSO> _upgradeById;

    /// <summary>Cached lookup: ending id -> ending asset.</summary>
    private Dictionary<string, EndingSO> _endingById;

    /// <summary>Cached lookup: nation id -> nation asset.</summary>
    private Dictionary<string, NationSO> _nationById;

    /// <summary>Cached lookup: place (profile) id -> place asset.</summary>
    private Dictionary<string, NationEraProfileSO> _profileById;

    /// <summary>Cached lookup: culture id ("neutral" or a nation id) -> theme.</summary>
    private Dictionary<string, ThemeSO> _themeById;

    /// <summary>Cached lookup: language -> UI string table.</summary>
    private Dictionary<string, UiStringTableSO> _tableByLanguage;

    /// <summary>
    /// Clears cached lookups when the asset is loaded/reloaded.
    /// This prevents stale dictionaries after domain reloads.
    /// </summary>
    private void OnEnable() => ResetLookups();

    /// <summary>
    /// Clears cached lookups when the asset changes in the editor (an
    /// inspector edit, or Generate World rewiring its arrays), so lookups in
    /// the same editor session never read the old arrays.
    /// </summary>
    private void OnValidate() => ResetLookups();

    /// <summary>Drops every cached lookup; the next lookup rebuilds them (EnsureLookups).</summary>
    private void ResetLookups()
    {
        _eraById = null;
        _effectByName = null;
        _upgradeById = null;
        _endingById = null;
        _nationById = null;
        _profileById = null;
        _themeById = null;
        _tableByLanguage = null;
    }

    /// <summary>
    /// Returns an Era by its string ID (e.g., "rome").
    /// Useful for saves or ID-based references.
    /// </summary>
    public EraSO GetEraById(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return null;

        EnsureLookups();
        return _eraById.TryGetValue(id, out EraSO era) ? era : null;
    }

    /// <summary>Returns a nation by its id ("china"), or null.</summary>
    public NationSO GetNationById(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return null;

        EnsureLookups();
        return _nationById.TryGetValue(id, out NationSO nation) ? nation : null;
    }

    /// <summary>Returns a place by its id ("china_future"), or null.</summary>
    public NationEraProfileSO GetProfileById(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return null;

        EnsureLookups();
        return _profileById.TryGetValue(id, out NationEraProfileSO profile) ? profile : null;
    }

    /// <summary>The theme of a culture id ("neutral" or a nation id), or null for an unknown or blank id.</summary>
    public ThemeSO GetThemeByCultureId(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return null;

        EnsureLookups();
        return _themeById.TryGetValue(id, out ThemeSO theme) ? theme : null;
    }

    /// <summary>The UI string table of a language ("en"), or null for an unknown or blank one.</summary>
    public UiStringTableSO GetStringTable(string language)
    {
        if (string.IsNullOrWhiteSpace(language))
            return null;

        EnsureLookups();
        return _tableByLanguage.TryGetValue(language, out UiStringTableSO table) ? table : null;
    }

    /// <summary>
    /// Returns an Upgrade by its string ID (e.g., "scanner").
    /// Used when loading save data that stores upgrade IDs.
    /// </summary>
    public UpgradeSO GetUpgradeById(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return null;

        EnsureLookups();
        return _upgradeById.TryGetValue(id, out UpgradeSO upgrade) ? upgrade : null;
    }

    /// <summary>
    /// Returns an Ending by its string ID (e.g., "fired", "bankrupt").
    /// Used by the title scene to display WorldState.endingId.
    /// </summary>
    public EndingSO GetEndingById(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return null;

        EnsureLookups();
        return _endingById.TryGetValue(id, out EndingSO ending) ? ending : null;
    }

    /// <summary>
    /// Returns an Effect by its asset name (effect.name).
    /// If you later add a stable id field to EffectSO, switch to that.
    /// </summary>
    public EffectSO GetEffectByAssetName(string assetName)
    {
        if (string.IsNullOrWhiteSpace(assetName))
            return null;

        EnsureLookups();
        return _effectByName.TryGetValue(assetName, out EffectSO effect) ? effect : null;
    }

    /// <summary>
    /// The DayPlan a day uses (DayPlans.Pick): the plan with that day number,
    /// else the latest earlier one, else null. Days after the last authored
    /// plan reuse it (the Future stays open once a leader exists).
    /// </summary>
    public DayPlanSO GetDayPlan(int dayNumber)
    {
        if (dayPlans == null)
            return null;

        DayPlanSO[] plans = dayPlans.Where(p => p != null).ToArray();
        int index = global::DayPlans.Pick(plans.Select(p => p.DayNumber).ToArray(), dayNumber);
        return index >= 0 ? plans[index] : null;
    }

    /// <summary>
    /// Builds internal dictionaries the first time they are needed.
    /// </summary>
    private void EnsureLookups()
    {
        if (_eraById != null)
            return;

        _eraById = new Dictionary<string, EraSO>(StringComparer.OrdinalIgnoreCase);
        _effectByName = new Dictionary<string, EffectSO>(StringComparer.OrdinalIgnoreCase);
        _upgradeById = new Dictionary<string, UpgradeSO>(StringComparer.OrdinalIgnoreCase);
        _endingById = new Dictionary<string, EndingSO>(StringComparer.OrdinalIgnoreCase);
        _nationById = new Dictionary<string, NationSO>(StringComparer.OrdinalIgnoreCase);
        _profileById = new Dictionary<string, NationEraProfileSO>(StringComparer.OrdinalIgnoreCase);
        _themeById = new Dictionary<string, ThemeSO>(StringComparer.OrdinalIgnoreCase);
        _tableByLanguage = new Dictionary<string, UiStringTableSO>(StringComparer.Ordinal);

        foreach (ThemeSO t in Themes.Prepend(neutralTheme))
            if (t != null && !string.IsNullOrWhiteSpace(t.cultureId))
                _themeById.TryAdd(t.cultureId, t);

        foreach (UiStringTableSO table in StringTables)
            if (table != null && !string.IsNullOrWhiteSpace(table.language))
                _tableByLanguage.TryAdd(table.language, table);

        if (nations != null)
            foreach (NationSO n in nations)
                if (n != null && !string.IsNullOrWhiteSpace(n.id))
                    _nationById.TryAdd(n.id, n);

        if (nationEraProfiles != null)
            foreach (NationEraProfileSO p in nationEraProfiles)
                if (p != null && !string.IsNullOrWhiteSpace(p.id))
                    _profileById.TryAdd(p.id, p);

        if (eras != null)
        {
            foreach (EraSO e in eras)
            {
                if (e == null || string.IsNullOrWhiteSpace(e.id))
                    continue;

                _eraById.TryAdd(e.id, e);
            }
        }

        if (effects != null)
        {
            foreach (EffectSO fx in effects)
            {
                if (fx == null)
                    continue;

                _effectByName.TryAdd(fx.name, fx);
            }
        }

        if (upgrades != null)
        {
            foreach (UpgradeSO u in upgrades)
            {
                if (u == null || string.IsNullOrWhiteSpace(u.id))
                    continue;

                _upgradeById.TryAdd(u.id, u);
            }
        }

        if (endings != null)
        {
            foreach (EndingSO e in endings)
            {
                if (e == null || string.IsNullOrWhiteSpace(e.id))
                    continue;

                _endingById.TryAdd(e.id, e);
            }
        }
    }
}
