using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;

/// <summary>
/// The Mail app's rules (redesign phase 25; the PC spec's ML1-ML2): the inbox
/// rebuilt from its sources by id, newest day first; the citation notices, the
/// directive memo, the Times issue and the authored mail; the read flags as
/// the only state; the authored mail's checks.
/// </summary>
public class MailboxTests
{
    private static MailSources Sources(int today, params CitationCopy[] citations) => new MailSources
    {
        Today = today,
        Rules = d => new[] { $"rule of day {d}" },
        News = d => d == today ? new[] { "headline" } : null,
        Citations = citations,
        Authored = new List<AuthoredMail>(),
        HasFlag = f => f == "set"
    };

    [Test]
    public void ForDays_ListsEachDaysMemoAndTimesNewestFirst()
    {
        List<MailItem> items = Mailbox.ForDays(Sources(3));

        CollectionAssert.AreEqual(new[] { "memo:3", "times:3", "memo:2", "times:2", "memo:1", "times:1" }, items.Select(i => i.Id).ToArray());
        Assert.AreEqual(MailLink.Rules, items[0].Link);
        Assert.AreEqual(MailLink.News, items[1].Link);
        CollectionAssert.AreEqual(new[] { "rule of day 2" }, items[2].Body, "the memo carries that day's directives");
    }

    [Test]
    public void ForDays_TimesBodyIsTheHeadlinesOrEmptyWhenNotArchived()
    {
        List<MailItem> items = Mailbox.ForDays(Sources(2));

        CollectionAssert.AreEqual(new[] { "headline" }, items.First(i => i.Id == "times:2").Body);
        Assert.IsTrue(items.First(i => i.Id == "times:2").IssueOnHand);
        CollectionAssert.IsEmpty(items.First(i => i.Id == "times:1").Body, "a past issue is only its link until phase 24 archives it");
        Assert.IsFalse(items.First(i => i.Id == "times:1").IssueOnHand);
    }

    [Test]
    public void ForDays_TodaysPaperWithoutHeadlinesIsStillOnHand()
    {
        MailSources s = Sources(1);
        s.News = d => new string[0];
        MailItem times = Mailbox.ForDays(s).Single(i => i.Kind == MailKind.TimesIssue);
        Assert.IsTrue(times.IssueOnHand);
        CollectionAssert.IsEmpty(times.Body);
    }

    [Test]
    public void ForDays_CitationsComeFirstInTheirDayLatestTravellerFirst()
    {
        List<MailItem> items = Mailbox.ForDays(Sources(2, new CitationCopy(2, 1, "slip one"), new CitationCopy(2, 4, "slip four"), new CitationCopy(1, 2, "old slip")));

        CollectionAssert.AreEqual(new[] { "cite:2:4", "cite:2:1", "memo:2", "times:2", "cite:1:2", "memo:1", "times:1" }, items.Select(i => i.Id).ToArray());
        MailItem four = items[0];
        Assert.AreEqual(MailKind.CitationNotice, four.Kind);
        Assert.AreEqual(4, four.Slot);
        CollectionAssert.AreEqual(new[] { "slip four" }, four.Body);
        Assert.AreEqual(MailLink.None, four.Link);
    }

    [Test]
    public void ForDays_AuthoredMailArrivesOnItsDayWhileInItsRangeAndFlag()
    {
        MailSources s = Sources(3);
        s.Authored = new[]
        {
            new AuthoredMail { id = "welcome", fromDay = 1, from = "Directorate", subject = "Welcome", body = new[] { "Hello." } },
            new AuthoredMail { id = "later", fromDay = 4, from = "x", subject = "y", body = new[] { "z" } },
            new AuthoredMail { id = "gone", fromDay = 1, untilDay = 2, from = "x", subject = "y", body = new[] { "z" } },
            new AuthoredMail { id = "flagged", fromDay = 2, flag = "set", from = "x", subject = "y", body = new[] { "z" } },
            new AuthoredMail { id = "waiting", fromDay = 2, flag = "unset", from = "x", subject = "y", body = new[] { "z" } }
        };

        List<MailItem> items = Mailbox.ForDays(s);
        string[] authored = items.Where(i => i.Kind == MailKind.Authored).Select(i => i.Id).ToArray();

        CollectionAssert.AreEqual(new[] { "mail:flagged", "mail:welcome" }, authored, "not yet arrived, past its last day and an unset flag are left out");
        MailItem welcome = items.Single(i => i.Id == "mail:welcome");
        Assert.AreEqual(1, welcome.Day);
        Assert.AreEqual("Directorate", welcome.From);
        Assert.AreEqual("Welcome", welcome.Subject);
        Assert.AreEqual("times:1", items[items.IndexOf(welcome) - 1].Id, "authored mail comes after the day's memo and Times");
    }

    [Test]
    public void ForDays_SameSourcesGiveTheSameIds()
    {
        MailSources s = Sources(4, new CitationCopy(4, 2, "slip"));
        CollectionAssert.AreEqual(Mailbox.ForDays(s).Select(i => i.Id), Mailbox.ForDays(s).Select(i => i.Id), "messages are regenerated by id, never saved");
    }

    /// <summary>The order log of <see cref="Deliveries_OneMemoPerDeliveryDay"/>: two arrivals on day 3 (in log order b, a), one on day 2, one still in transit.</summary>
    private static MailSources WithDeliveries(int today)
    {
        MailSources s = Sources(today);
        s.Orders = new List<OrderEntry>
        {
            new OrderEntry { upgradeId = "b", orderedDay = 2, price = 10, deliveredDay = 3 },
            new OrderEntry { upgradeId = "c", orderedDay = 1, price = 10, deliveredDay = 2 },
            new OrderEntry { upgradeId = "a", orderedDay = 2, price = 10, deliveredDay = 3 },
            new OrderEntry { upgradeId = "d", orderedDay = 3, price = 10 }
        };
        s.UpgradeName = id => id.ToUpperInvariant() + " scanner";
        return s;
    }

    [Test]
    public void Deliveries_OneMemoPerDeliveryDay()
    {
        List<MailItem> items = Mailbox.ForDays(WithDeliveries(3));

        CollectionAssert.AreEqual(new[] { "delivery:3", "delivery:2" }, items.Where(i => i.Kind == MailKind.Delivery).Select(i => i.Id).ToArray());
        CollectionAssert.AreEqual(new[] { "memo:3", "times:3", "delivery:3", "memo:2", "times:2", "delivery:2", "memo:1", "times:1" }, items.Select(i => i.Id).ToArray(),
                                  "the delivery arrives with the morning's memo and paper");
        Assert.AreEqual(MailLink.None, items.Single(i => i.Id == "delivery:2").Link);
    }

    [Test]
    public void Deliveries_ListTheItemsInLogOrder()
    {
        MailItem three = Mailbox.ForDays(WithDeliveries(3)).Single(i => i.Id == "delivery:3");

        Assert.AreEqual(3, three.Day);
        CollectionAssert.AreEqual(new[] { "B scanner", "A scanner" }, three.Body, "named, in the order they were ordered");
    }

    [Test]
    public void Deliveries_APendingOrderSendsNothing()
    {
        MailSources s = WithDeliveries(4);
        s.Orders = new List<OrderEntry> { new OrderEntry { upgradeId = "d", orderedDay = 4, price = 10 } };

        Assert.IsFalse(Mailbox.ForDays(s).Any(i => i.Kind == MailKind.Delivery));
        s.Orders = null;
        Assert.IsFalse(Mailbox.ForDays(s).Any(i => i.Kind == MailKind.Delivery), "no log, no memo");
    }

    [Test]
    public void Deliveries_IdIsDeliveryAndTheDay_AndAnUnnamedItemKeepsItsId()
    {
        MailSources s = WithDeliveries(2);
        s.UpgradeName = null;

        MailItem two = Mailbox.ForDays(s).Single(i => i.Kind == MailKind.Delivery);

        Assert.AreEqual("delivery:2", two.Id);
        CollectionAssert.AreEqual(new[] { "c" }, two.Body);
    }

    [Test]
    public void UnreadAndMarkRead_CountTheMessagesNotOpened()
    {
        List<MailItem> items = Mailbox.ForDays(Sources(2));
        var read = new List<string>();

        Assert.AreEqual(4, Mailbox.Unread(items, read));
        Assert.IsTrue(Mailbox.MarkRead(read, "memo:2"));
        Assert.IsFalse(Mailbox.MarkRead(read, "memo:2"), "no duplicate flag");
        Assert.IsFalse(Mailbox.MarkRead(read, ""));
        Assert.AreEqual(3, Mailbox.Unread(items, read));
        CollectionAssert.AreEqual(new[] { "memo:2" }, read);
    }

    [Test]
    public void Unread_IgnoresFlagsOfMessagesNoLongerListed()
    {
        List<MailItem> items = Mailbox.ForDays(Sources(1));
        Assert.AreEqual(2, Mailbox.Unread(items, new List<string> { "cite:9:1", "mail:gone" }));
    }

    [Test]
    public void AuthoredProblems_RefuseBrokenMessages()
    {
        var mail = new[]
        {
            new AuthoredMail { id = "ok", fromDay = 1, from = "a", subject = "b", body = new[] { "c" } },
            new AuthoredMail { id = "ok", fromDay = 1, from = "a", subject = "b", body = new[] { "c" } },
            new AuthoredMail { id = "", fromDay = 0, untilDay = -1, from = " ", subject = "", body = new[] { " " } }
        };

        List<string> problems = Mailbox.AuthoredProblems(mail);

        Assert.IsTrue(problems.Any(p => p.Contains("'ok' is listed twice")));
        Assert.IsTrue(problems.Any(p => p.Contains("mail[2] has no id")));
        Assert.IsTrue(problems.Any(p => p.Contains("fromDay 0")));
        Assert.IsTrue(problems.Any(p => p.Contains("untilDay -1")));
        Assert.IsTrue(problems.Any(p => p.Contains("no sender")));
        Assert.IsTrue(problems.Any(p => p.Contains("no subject")));
        Assert.IsTrue(problems.Any(p => p.Contains("no body")));
        CollectionAssert.IsEmpty(Mailbox.AuthoredProblems(new[] { mail[0] }));
    }
}
