using System.Linq;
using static ColumnSpec;
using static SheetSpec;

/// <summary>
/// The content spreadsheet's map of Assets/Data/World/world_source.json: one sheet per
/// table, one column per field, in the JSON's own order, with each column's type and
/// rules as data. The engine (<see cref="ContentSheets"/>) reads nothing else, so a new
/// section of the source is a new entry here:
/// <list type="bullet">
/// <item>a new field: a column where the JSON orders it (<c>Text("kinds")</c>, <c>.Omit()</c> when the JSON leaves it out at its default, <c>.Ref("sheet")</c> when it names another sheet's row);</item>
/// <item>a new list of objects: <c>Rows("sheetName", "jsonKey", Key("id", "childHeader"), columns...)</c> where the JSON orders it (Key only when rows have child sheets or are referred to);</item>
/// <item>a list of plain values: <c>List("jsonKey")</c> for ids ("a|b" in one cell) or <c>Values("sheetName", "jsonKey", Text("text"))</c> for sentences;</item>
/// <item>a nested object: dotted column paths ("culture.language"), or <c>Single</c> under a one-row sheet.</item>
/// </list>
/// The round-trip test (ContentSheetMapTests) fails, naming the JSON path, until every key
/// of the source is mapped. Sheet names are at most 31 characters (Excel's limit).
/// </summary>
public static class ContentSheetMap
{
    /// <summary>The whole map, rooted at the document.</summary>
    public static readonly SheetSpec World =
        Single("world", "",
            Int("travellerAgeMin").Note("youngest ordinary traveller"),
            Int("travellerAgeMax").Note("oldest ordinary traveller"),
            Looks(),
            Content(),
            Single("agency", "agency",
                Text("name").Note("the agency's printed name"),
                Text("programme"),
                Text("firstDate").Note("the desk calendar's date on day 1"),
                Int("displaced.foundWithinDays").Note("a displaced person was found 1 to this many days before today"),
                Int("displaced.validDaysMin").Note("the fewest days after today a Displacement Certificate is valid"),
                Int("displaced.validDaysMax").Note("the most days after today a Displacement Certificate is valid"),
                Text("clerk.citizenId").Note("the clerk's own Citizen Account (the Citizen Account app)"),
                Text("clerk.name"),
                Text("clerk.born"),
                Text("clerk.lineage"),
                Text("clerk.employment"),
                Text("clerk.note"),
                Int("clerk.startDebt").Note("the clerk's own debt at the start of a run, in cr"),
                Num("clerk.garnishShare").Note("the share of each shift's pay that goes to the clerk's debt (0.25 = 25%)"),
                Text("clerk.reliefEmployer").Note("the clerk's own Debt Relief Labour Contract on the bankrupt ending"),
                Text("clerk.reliefWorksite"),
                Int("clerk.reliefWage").Note("the contract's day wage in cr; its term is the debt at this wage"),
                Single("agencyAccounts", "accounts",
                    Int("validDaysMin").Note("the fewest days after today a citizen's honest paper is valid"),
                    Int("validDaysMax").Note("the most days after today a citizen's honest paper is valid"),
                    Int("tripsWithinDays").Note("a past trip on an account left 1 to this many days ago"),
                    Int("frozenWithinDays").Note("a Frozen account went into default 1 to this many days ago"),
                    Text("waiverPrefix").Note("the Stranding Waiver number's prefix (SW gives SW-204817)"),
                    Rows("agencyStatuses", "statuses",
                        Text("status").Required().OneOf("Premium", "Standard", "Eligible"),
                        Int("debtMin"),
                        Int("debtMax"),
                        Int("tripsMin"),
                        Int("tripsMax")).Note("each account status's debt and past trips"),
                    Int("contract.termMin").Note("a labourer's registered contract: the shortest term in days (whole 30-day months)"),
                    Int("contract.termMax").Note("the longest term in days"),
                    Int("contract.wageMin").Note("the lowest day wage in cr"),
                    Int("contract.wageMax").Note("the highest day wage in cr")).Note("the ranges a 2150 citizen's Citizen Account is drawn from"),
                Rows("agencyTransponders", "transponders", Key("id"),
                    Text("id").Required(),
                    Text("transponderClass").OneOf("Premium", "Economy"),
                    Text("model"),
                    Text("prefix").Note("the serial's prefix (HP gives HP-40718)"),
                    Num("weight")).Note("the transponder models citizens travel on, weighted per class"),
                Rows("agencyProofs", "proofs",
                    Text("form").Required().Note("the proof's form (TC-415, TC-416 or TC-417)"),
                    Text("category").OneOf("Credit", "Funds", "PolicyNo").Note("the record category the proof is compared under"),
                    Num("weight").Note("its weight in a poor tourist's draw"),
                    Int("amountMin").Note("an amount proof's least value in cr (0 for a number)"),
                    Int("amountMax").Note("an amount proof's most value in cr (0 for a number)"),
                    Text("prefix").Note("a number proof's prefix (TI gives TI-551902); blank for an amount")).Note("the proofs of means a Standard account may hold, one per proof form"),
                Num("strandChance").Note("the chance an accepted traveller on an Economy transponder is stranded at the shift's end (0.08 = 8%)"),
                Rows("agencyStrandingFates", "strandingFates", Key("id", "strandingFate"),
                    Text("id").Required(),
                    Text("fate").OneOf(System.Enum.GetNames(typeof(StrandingFate))).Note("what the fate does: Forgotten (Mail only), News (the paper), Carry (2150 technology), Tremor (stability), Police (the Time Police)"),
                    Num("weightWaivered").Note("its weight when a valid signed waiver was on file (never shown to the player)"),
                    Num("weightUnwaivered").Note("its weight when none was"),
                    Num("stability").Omit().Note("a tremor's loss: the percent of where stability stands (blank for every other fate)"),
                    Text("status").Note("the failure report's last line"),
                    Rows("strandingFateLines", "lines",
                        Text("era").Omit().Ref("eras").Note("the destination's era (blank: any)"),
                        Text("text").Note("the morning paper's line: {place} required, {name} optional")).OmitEmpty().Note("a fate's paper lines (none for Forgotten; none elsewhere prints news.stranded)"))
                    .Note("what becomes of a stranded traveller: one fate per stranding, weighted by the waiver (the endings and strandings spec §6)"),
                Single("agencyStrandingReport", "strandingReport",
                    Text("unit").Note("the failure report's unit line: {unit}, {place}"),
                    Text("traveller").Note("{name}, {id}"),
                    Text("waivered").Note("a valid signed waiver on file: {waiver}, {debt}"),
                    Text("unwaivered").Note("no valid signed waiver on file"),
                    Text("fine").Note("the stranding fine charged: {fine}")).Note("the agency's transponder failure report, Mail's message for every stranding"),
                Rows("agencyEmployers", "employers", Key("id"),
                    Text("id").Required(),
                    Text("era").Ref("eras").Note("the era the employer hires for"),
                    Text("name").Note("the printed name on a labourer's contract")).Note("the Debt Relief programme's employers: a labourer's contract names one of the worksite's era"),
                Rows("agencyPortals", "portals", Key("number"),
                    Int("number").Required().Note("the ring's number as the art numbers it (01 front ... 05 upper right)"),
                    Text("name").Note("the ring's name, printed in the Portals app and the board's tooltip"),
                    Text("role").OneOf("Departures", "Returns").Note("Departures run the Directorate's route each day; Returns is the Return Gate, the displaced's way home"),
                    Int("fromDay").Omit().Note("the day it enters service by itself; blank: only by its repair"),
                    Text("repair").Omit().Note("the upgrade id whose delivery puts it in service (an Orders node)")).OmitEmpty().Note("the hall's portals: one row per ring"),
                Rows("agencyOffices", "offices", Key("id"),
                    Text("id").Required(),
                    Text("name").Note("the office's printed name: the programme line of every form it issues and its Seal Register row"),
                    Text("shape").OneOf(System.Enum.GetNames(typeof(SealShape))).Note("the seal's outline; every office's outline and ink differ"),
                    Text("ink").OneOf(System.Enum.GetNames(typeof(SealInk))).Note("the seal's ink"),
                    Text("legend").Note("the initials inside the seal (1 to 3 capitals)"),
                    Text("forgedLegend").Note("the initials a forger prints instead (as many capitals, no office's legend)"),
                    List("forms").Note("the forms it issues (TC-101|...); every traveller form has one office")).Note("the issuing offices: each prints its seal on its forms, pictured in the Seal Register (a forged seal differs in outline, ink or legend)"),
                Rows("agencyFaults", "faults", Key("id"),
                    Text("id").Required(),
                    Text("form").Note("the form the fault is on (TC-101), or * for any paper (a forged seal)"),
                    Text("field").Note("the category it prints on (a ClueCategory name); blank: the whole paper (a missing form)"),
                    Text("lie").Note("the lie that prints it (a LieKind name); blank for a directive fault"),
                    Text("directive").Note("the directive fault it breaks (a DirectiveFault name); blank for a lie"),
                    Text("variant").Note("a lie's rows of one variant are forged together, in row order"),
                    Bool("optional").Omit().Note("forged only when its form is carried (the variant shows without it)"),
                    Text("against").Note("what proves it, in the player's words"),
                    Text("note").Note("what the forger did, in one line")).Note("the published fault canon: every fault a document can carry; the case factory draws only from it (docs/DOCUMENT_FAULTS.md)")),
            Rows("eras", "eras", Key("id", "era"),
                Text("id").Required(),
                Text("displayName"),
                Int("order"),
                Bool("future").Omit().Note("the office's own time (at most one era)"),
                Text("group").Omit().Ref("eras").Note("the main era this one is a second moment of (blank: a main era): a nation's second place of that era, shown under the main era's name"),
                Values("eraSmallTalk", "smallTalk", Text("text")).Note("small talk any traveller of the era may say")),
            Countries(),
            Places(),
            Present(),
            Rows("rules", "rules", Key("asset"),
                Text("asset").Required().Note("the rule asset's name"),
                Text("type"),
                Text("country").Omit().Ref("countries").Note("a closure's country (blank: none)"),
                Text("era").Omit().Ref("eras").Note("a closure's era (blank: none)"),
                Text("description"),
                List("kinds").Omit().Note("a paper set's, debt standing's or recall's kinds (RichTourist, PoorTourist, Labourer, Displaced); blank: every kind"),
                Text("transponder").Omit().Ref("agencyTransponders").Note("the model a recall (TransponderRecall) grounds; blank for every other rule")).Note("travel rules a day can switch on: closures and standing procedures"),
            Days(),
            PersonalitiesSheet(),
            Interview(),
            Questions(),
            Dialogs(),
            Premades(),
            History(),
            Single("news", "news",
                Text("stranded").Note("the morning paper's line per traveller stranded the day before: {name} and {place}"),
                Text("debtReliefCount").Note("the morning paper's count of the Debt Relief departures the last shift approved: {count}"),
                Text("returnedAccepted").Note("the desk section's line for a traveller turned away who came back and was let through: {name}, {day} (the first denial), {back} (the return)"),
                Text("returnedDenied").Note("the desk section's line for a traveller turned away twice: {name}, {day}, {back}"),
                Values("newsDebt", "debt", Text("text")).Note("the morning paper's debt lines: one a day, in a shuffled order per run")).Note("the morning paper's debt-theme lines"),
            Pc(),
            Ui(),
            Translation(),
            Home(),
            Rows("worldFactors", "world.factors", Key("id"),
                Text("id").Required().Note("the factor's id (the outcomes, leanings and pulls name their factor by it)"),
                Text("question").Note("the question the end of the demo answers about 2150"),
                Text("answer").OneOf("AsFound", "Leader", "Pulls").Note("AsFound: the foundAs text; Leader: the leading nation's name (foundAs while none leads); Pulls: the outcome the run's choices pull most (worldOutcomes)"),
                Text("foundAs").Omit().Note("the answer as the run found 2150 (a Pulls factor's is its statusQuo outcome: blank)"),
                Text("statusQuo").Omit().Note("a Pulls factor's \"as you found it\" outcome id: it starts ahead (GameConfigSO worldStatusQuoWeight) and a denial pulls it"),
                Text("splitLine").Omit().Note("a Pulls factor's answer when split between two outcomes: {a} and {b} are their names"),
                Text("splitHeadline").Omit().Note("the morning paper's line when the factor splits: {a} and {b}")).Note("the world's outcomes listed under END OF DEMO, in this order"),
            Rows("worldOutcomes", "world.outcomes",
                Text("factor").Required().Ref("worldFactors").Note("the factor it answers (a Pulls factor)"),
                Text("id").Required().Note("the outcome's id within its factor (leanings and pulls name it)"),
                Text("name").Note("the answer as the player reads it"),
                Text("headline").Note("the morning paper's line the morning after it takes the lead"),
                Text("report").Note("2150 under this answer in a sentence or two, with a joke and an upside, never a verdict")).Note("every answer of every factor answered by pulls: add rows for more combinations"),
            Rows("worldRoles", "world.roles",
                Text("archetype").Required().Note("an archetype id (content.archetypes)"),
                Text("factor").Ref("worldFactors").Note("the factor its accepted travellers pull, toward their destination's leaning"),
                Num("pull").Note("one accepted traveller's pull, before the kind's scale (GameConfigSO)")).Note("which factor each role pulls; a role not listed pulls nothing"));

    private static SheetSpec Looks() =>
        Single("looks", "looks",
            Rows("faceBands", "faceBands",
                Int("minAge"),
                List("faces")),
            Int("greyFromAge"),
            Text("wholeFigureLabel"),
            Num("costumeErrors.otherPlace").Note("weight of a costume error that is another of today's places' item"),
            Num("costumeErrors.presentClothes").Note("weight of a costume error that is the present's whole look (2150 clothes)"),
            Num("costumeErrors.presentAccessory").Note("weight of a costume error that is one 2150 accessory"),
            Rows("confusable", "confusable",
                Text("a").Ref("places"),
                Text("b").Ref("places"),
                Text("slot"),
                Text("gender"),
                Text("why").Note("a note for reviewers")).Note("two places whose items in a slot look alike"));

    private static SheetSpec Content() =>
        Single("content", "content",
            Text("library"),
            Rows("contentBlueprints", "blueprints",
                Text("kind").Required().OneOf("RichTourist", "PoorTourist", "Labourer", "Displaced"),
                Text("asset")).Note("each traveller kind's case blueprint"),
            Text("dayPlanFolder"),
            Rows("contentAttributes", "attributes", Key("id"),
                Text("id").Required(),
                Text("asset")),
            Values("contentArchetypes", "archetypes", Text("asset")),
            Values("contentBooks", "books", Text("asset"))).Note("the authored assets the world is wired into (asset paths)");

    private static SheetSpec Countries() =>
        Rows("countries", "countries", Key("id", "country"),
            new SheetField[]
            {
                Text("id").Required(),
                Text("displayName"),
                Rows("countryBaselines", "baselines",
                    Text("attribute").Ref("contentAttributes"),
                    Float("score")),
                Nums("looks.skin").Note("skin tone weights 1..5"),
                Rows("countryHair", "looks.hair",
                    Text("colour"),
                    Num("weight")),
            }.Concat(Culture("culture.", "country")).ToArray());

    private static SheetSpec Places() =>
        Rows("places", "places", Key("{country}_{era}", "place"),
            Text("country").Required().Ref("countries"),
            Text("era").Required().Ref("eras"),
            Text("displayName"),
            Text("moment").Note("the place's moment in a sentence (Chronopedia's article)"),
            Int("year"),
            Text("tongue").Ref("tongues"),
            Rows("placeFacts", "facts",
                Text("category"),
                Text("value")),
            List("maleNames"),
            List("femaleNames"),
            Values("placeSmallTalk", "smallTalk", Text("text")).OmitEmpty(),
            Wardrobe("wardrobe", "wardrobe"),
            Nums("looks.skin").Omit().Note("overrides the country's skin weights"),
            Rows("placeHair", "looks.hair",
                Text("colour"),
                Num("weight")).OmitEmpty().Note("overrides the country's hair weights"),
            Rows("placeLeanings", "leanings",
                Text("factor").Ref("worldFactors"),
                Text("outcome").Note("an outcome id of the factor (worldOutcomes)")).OmitEmpty().Note("where an idea has roots: an accepted traveller sent here pulls the factor toward this outcome (no row: nowhere)"))
            .Note("a place is a country in an era; child sheets name it {country}_{era}");

    /// <summary>The neutral present (the present while no nation leads): its name, year and facts; its clothes (its Culture fact is derived from them, and a 2150 citizen who forgot their costume wears them whole) and its 2150 accessory kit (costume errors).</summary>
    private static SheetSpec Present() =>
        Single("present", "present",
            Text("displayName"),
            Int("year"),
            Rows("presentFacts", "facts",
                Text("category"),
                Text("value")),
            Wardrobe("presentWardrobe", "wardrobe").Note("the present's clothes, worn whole by a 2150 citizen who forgot their costume"),
            Rows("presentKit", "kit",
                Text("gender").Required().OneOf("m", "f"),
                Text("label").Required(),
                Text("variant").Required().Note("the art key token: accessory_{gender}_neutral_future_{variant}"))
                .Note("the present's 2150 accessory kit, one item per row: one can slip onto a right costume (a costume error)"))
            .Note("the present, 2150, while no nation leads: never a destination; every book lists its row");

    /// <summary>A wardrobe at <paramref name="path"/>: per gender its signature slot and one worn item per slot (a place's, or the present's).</summary>
    private static SheetSpec Wardrobe(string name, string path) =>
        Keyed(name + "Sets", path, Text("gender").OneOf("m", "f"),
            Text("signature").Note("the slot whose item is the dress signature"),
            Keyed(name, "", Text("slot").OneOf("outfit", "hair", "facialHair", "headwear", "accessory"),
                Text("label").Required(),
                Bool("wig").Omit(),
                Bool("back").Omit(),
                Bool("leakable").Omit(),
                List("covers").Omit().Note("slots this item hides"),
                Text("artNation").Omit().Note("files the art under another nation (blank: the place's own)")).Note("one worn item per row"));

    private static SheetSpec Days() =>
        Rows("days", "days", Key("day", "day"),
            Text("asset").Required(),
            Int("day").Required(),
            Int("queue"),
            Text("bulletin").Note("the morning briefing's first line: the one paper or check the day brings for the first time (blank: nothing new; lesson 4)"),
            List("papers").Note("the form numbers in circulation this day (TC-101 ...): travellers carry only these, never one an earlier day issued left out; empty: every form (lesson D7)"),
            Int("tells"),
            List("channels"),
            List("lies").Note("the lies enabled this day (FalseOrigin, PoorPosingAsRich, DoctoredIdentity, FakeDisplaced, Smuggling, DebtorPosingAsTourist, ForgedContract, FakeWaiver, ForgedProof); a traveller draws among those that fit their kind"),
            Rows("dayKinds", "kinds",
                Text("kind").Required().OneOf("RichTourist", "PoorTourist", "Labourer", "Displaced"),
                Num("weight"),
                Bool("honest").Omit().Note("true: its travellers are honest, no fault is rolled (day 1's poor tourists)")).Note("the day's traveller mix: each kind's weight"),
            Rows("dayEras", "eras",
                Text("era").Ref("eras"),
                Num("weight")),
            List("countries").Ref("countries"),
            List("rules").Ref("rules"),
            List("premades").Ref("premades").Note("premades that may roll this day"),
            Rows("dayForced", "forced", Key("{slot}{id}", "forced").Optional("id"),
                Int("slot"),
                Text("premade").Ref("premades"),
                Text("blueprint"),
                Text("id").Omit().Note("the appearance's name (days 7-15): needed when a slot lists alternatives, which are tried in order, the first whose conditions pass standing; unique in the day"),
                Text("lie").Omit().OneOf(System.Enum.GetNames(typeof(LieKind))).Note("an authored lie the appearance tells (blank: none)"),
                Text("directive").Omit().OneOf(System.Enum.GetNames(typeof(PlannedDirective)).Skip(1).ToArray()).Note("an authored directive fault (blank: none): the maker's variant pinned"),
                Text("dialog").Omit().Ref("dialogs").Note("the appearance's dialog, replacing the premade's (blank: the premade's)"),
                Text("intro").Omit().Note("the desk's opener for the appearance (blank: the premade's, else the interview's)"),
                GateConditions("dayForcedConditions").OmitEmpty().Note("when the appearance stands (all must pass at the day's start; none: always)")).Note("forced slots: a premade, a blueprint or both, and a beat's fault, voice and conditions"),
            Float("premadeChance"),
            Float("costumeErrorChance").Note("chance per 2150 citizen of a costume error (0 before the dress rule's first day)"),
            Float("slipChance").Note("chance per generated liar of a slip after small talk (the personalities spec's T9; 0 never)"),
            Float("violationChance").Note("chance per honest traveller of breaking a rolled procedure, the paper set or the debt standing (0 before their first day)"),
            Int("returns").Omit().Note("the most travellers turned away earlier who may come back that day, same name and face (0: none; the chance and the days are Game Config knobs)"),
            Rows("dayPortals", "portals",
                Int("portal").Required().Ref("agencyPortals"),
                Text("country").Ref("countries"),
                Text("era").Ref("eras")).OmitEmpty().Note("the Directorate's route for each departure portal that day (a place of the day's world; a route a closure forbids shows CLOSED)"));

    private static SheetSpec Interview() =>
        Single("interview", "interview",
            Text("deskName"),
            Text("opener"),
            Text("openerLegendary"),
            Text("openerReturning").Note("the desk's opener for a traveller back after a denial: {honorific} and {day} (the day they were turned away)"),
            Rows("claims", "claims",
                Text("kind").Required().OneOf("RichTourist", "PoorTourist", "Labourer", "Displaced"),
                Text("text")).Note("the claim per traveller kind ({place}): one row per kind a blueprint makes"),
            Text("honorificMale"),
            Text("honorificFemale"),
            Text("honorificUnknown"),
            Text("requestLabel"),
            Text("papersLabel").Note("the hub entry that opens the papers menu"),
            Rows("askGroups", "askGroups", Key("id"),
                Text("id").Required().Note("the request group (DocumentTemplateSO.askGroup; proof: the proofs of means)"),
                Text("label").Note("the papers menu's one entry for the group")).Note("request groups: several forms as one request"),
            Text("requestPrompt"),
            Text("requestReply"),
            Text("askLabel").Note("the ask entry, the same for every traveller"),
            Text("backLabel"),
            Text("smallTalkLabel"),
            Text("smallTalkPrompt"),
            Rows("interviewRequests", "requests", Key("id"),
                Text("id").Required(),
                Text("label"),
                Text("prompt"),
                Text("reply")).Note("spoken requests: the wheel entry, the desk's prompt and the traveller's reply"),
            Rows("missingFormReplies", "missingFormReplies",
                Text("kind").Required().OneOf("RichTourist", "PoorTourist", "Labourer", "Displaced"),
                Text("request").Required().Note("a form number (TC-310) or a request group's id (proof)"),
                Text("variant").OneOf("Honest", "Missing").Note("Honest: the kind never needs it; Missing: they should have it (a paper-set fault)"),
                Text("text")).Note("what a kind says when asked for a request they carry no form of"),
            Int("menuCapacity"),
            Int("maxLineChars"),
            Text("lookLabel"),
            Text("faceLabel").Note("the look menu's entry for the traveller's face: a photo is held against it"),
            Num("smallTalkWeights.personality").Note("small talk's sources are picked by weight: the personality's own lines"),
            Num("smallTalkWeights.home").Note("the home's lines (a displaced person's claimed place, else its era; a 2150 citizen's present, else the Future era)"),
            Num("smallTalkWeights.kind").Note("the kind's lines (kindSmallTalk)"),
            Rows("kindSmallTalk", "kindSmallTalk",
                List("kinds").Note("the kinds that say it (RichTourist, PoorTourist, Labourer, Displaced)"),
                Text("era").Omit().Ref("eras").Note("the claimed era (blank: any)"),
                Text("text")).Note("the kinds' small talk: one of small talk's three sources"),
            VoiceSheet("voiceClaims", "voices.claims", "the claim in a voice ({place} required)"),
            VoiceSheet("voiceHandOver", "voices.handOver", "the reply as a paper is handed over ({document}, {place})",
                Text("request").Omit().Note("the request it is for (a form number or a group id; blank: any)")),
            VoiceSheet("voiceMissingForms", "voices.missingForms", "a refusal in character of a form the traveller does not carry ({document}, {place})",
                Text("request").Required().Note("a form number (TC-310) or a request group's id (proof)"),
                Text("variant").OneOf("Honest", "Missing").Note("Honest: the kind never needs it; Missing: they should have it")),
            VoiceSheet("voiceSpoken", "voices.spoken", "the reply to a spoken request ({place})",
                Text("request").Required().Ref("interviewRequests")),
            VoiceSheet("voiceAnswers", "voices.answers", "an answer in a voice ({value} required, {place})",
                Text("question").Required().Ref("questions")),
            VoiceSheet("voiceSmallTalk", "voices.smallTalk", "a personality's or a premade's small talk ({place}; a premade's is its only source)"),
            Rows("interviewReactions", "reactions",
                Text("verdict").OneOf("Accepted", "Denied"),
                Text("intent").OneOf("Honest", "Lying").Note("Lying: a place lie, smuggling or a record lie; Honest otherwise (a directive fault or a costume error included)"),
                Text("reason").Omit().Note("a fault reason (forged, disguised, smuggled, closed, wrongDate, expired, incomplete, frozen, panic; blank: any)"),
                List("kinds").Omit().Note("the kinds it is for (blank: any)"),
                Text("era").Omit().Ref("eras").Note("the claimed era (blank: any)"),
                Text("text"),
                Text("then").Omit().Note("an optional second line")).Note("the default reactions to the stamp: the four verdict x intent rows with a blank reason, kinds and era are required"),
            Rows("interviewSlips", "slips",
                Text("lie").Omit().Note("a lie kind (FalseOrigin, PoorPosingAsRich, DoctoredIdentity, FakeDisplaced, Smuggling...; blank: any)"),
                List("kinds").Omit().Note("the kinds it is for (blank: any)"),
                Text("era").Omit().Ref("eras").Note("the claimed era (blank: any)"),
                Text("text")).Note("the default slips a liar says after small talk (one with a blank lie is required; never a checkable value)"),
            VoiceSheet("voiceReactions", "voices.reactions", "a reaction to the stamp in a voice ({place} in both lines)",
                new ColumnSpec[]
                {
                    Text("verdict").OneOf("Accepted", "Denied"),
                    Text("intent").OneOf("Honest", "Lying"),
                    Text("reason").Omit().Note("a fault reason (blank: any)")
                },
                Text("then").Omit().Note("an optional second line")),
            VoiceSheet("voiceSlips", "voices.slips", "a liar's slip in a voice ({place}; never a checkable value)",
                Text("lie").Omit().Note("a lie kind (blank: any)")),
            VoiceSheet("voiceWaiverPad", "voices.waiverPad", "the answer to the desk's waiver pad in a voice ({place}): every personality signs and refuses in its own words",
                Text("reply").Required().OneOf(System.Enum.GetNames(typeof(WaiverPadReply)))),
            VoiceSheet("voiceConfront", "voices.confront", "the answer to the desk's question about a logged difference in a voice ({value}, {other}, {place}): every personality explains, cracks and doubles down in its own words",
                Text("outcome").Required().OneOf(System.Enum.GetNames(typeof(ConfrontOutcome))).Note("Explain: an honest traveller (a clerical slip; it clears nothing); Crack: a liar confesses; DoubleDown: a liar insists"),
                Text("reason").Omit().Note("a fault reason (forged, disguised, smuggled, panic...; blank: any)"),
                Text("lie").Omit().Note("a lie kind (blank: any)")),
            Single("waiverPad", "waiverPad",
                Text("label").Note("the entry every traveller of a day whose papers menu holds the waiver is offered"),
                Text("prompt").Note("what the desk says as it slides a blank across"),
                Rows("waiverPadReplies", "replies",
                    Text("reply").Required().OneOf(System.Enum.GetNames(typeof(WaiverPadReply))),
                    List("kinds").Omit().Note("the kinds it is for (blank: any)"),
                    Text("era").Omit().Ref("eras").Note("the claimed era (blank: any)"),
                    Text("text")).Note("the default replies: one base row per reply is required")).Note("the desk's waiver pad (the endings and strandings spec §7.3)"),
            Single("confront", "confront",
                Text("label").Note("the hub entry that opens the questions about the differences the clerk logged (shown while one is still to be asked)"),
                Text("entryLabel").Note("one difference's entry: {category} and {value}"),
                Rows("confrontPrompts", "prompts",
                    Text("proof").Required().OneOf(System.Enum.GetNames(typeof(DiscrepancyProof))),
                    Text("source").Required().OneOf("DocumentField", "Answer", "Appearance").Note("what the statement was: papers, said or worn (a cross proof is always DocumentField)"),
                    Text("category").Omit().Note("the clue category it is for (blank: any)"),
                    Text("text").Note("the desk's question: {value} and {other} required (here or in then); {category}, {place}, {document} (papers) and {otherDocument} (a cross proof) allowed"),
                    Text("then").Omit().Note("an optional second desk line (each line fits a transcript row)")).Note("the desk's questions: one base row (blank category) per proof and statement kind is required"),
                Rows("confrontReplies", "replies",
                    Text("outcome").Required().OneOf(System.Enum.GetNames(typeof(ConfrontOutcome))),
                    Text("reason").Omit().Note("a fault reason (blank: any)"),
                    Text("lie").Omit().Note("a lie kind (blank: any)"),
                    List("kinds").Omit().Note("the kinds it is for (blank: any)"),
                    Text("era").Omit().Ref("eras").Note("the claimed era (blank: any)"),
                    Text("text").Note("{value}, {other} and {place} allowed")).Note("the default answers: one base row per outcome is required")).Note("the wheel's questions about logged differences (wave 5, lesson 3)")).Note("the interview's wording");

    /// <summary>The cast (world_source.json "personalities"; the personalities spec's PS1-PS2).</summary>
    private static SheetSpec PersonalitiesSheet() =>
        Rows("personalities", "personalities", Key("id", "personality"),
            Text("id").Required(),
            Text("name"),
            Num("weight").Note("its weight in the draw, the same for every kind (0 benches it)"),
            Text("note").Note("for authors: the tone in one line (never shown in the game)"),
            Num("waiverRefusal").Note("the chance they refuse the desk's waiver pad, in character (0 to 1; never shown)"),
            Text("strandingFate").Omit().OneOf(System.Enum.GetNames(typeof(StrandingFate))).Note("the stranding fate their tilt multiplies (blank: none)"),
            Num("confess").Note("the chance a lying traveller cracks when the desk asks about a difference the clerk logged (0 to 1; otherwise they double down; never shown)")).Note("the cast: every generated traveller is one of them; the premades speak their own lines");

    /// <summary>One voice slot's sheet (interview.voices.{list}; the personalities spec's §9.1): the voice (a personality or a premade, exactly one), the slot's keys, the kinds and era it is for, the line.</summary>
    private static SheetSpec VoiceSheet(string sheet, string path, string note, params ColumnSpec[] keys) =>
        VoiceSheet(sheet, path, note, keys, null);

    /// <summary>A voice slot's sheet with <paramref name="tail"/> after the text (a reaction's then line).</summary>
    private static SheetSpec VoiceSheet(string sheet, string path, string note, ColumnSpec[] keys, ColumnSpec tail) =>
        Rows(sheet, path,
            new[]
            {
                Text("personality").Omit().Ref("personalities").Note("the personality that says it (or a premade)"),
                Text("premade").Omit().Ref("premades").Note("the premade that says it (or a personality)")
            }
            .Concat(keys)
            .Concat(new[]
            {
                List("kinds").Omit().Note("the kinds it is for (blank: any)"),
                Text("era").Omit().Ref("eras").Note("the claimed era (blank: any)"),
                Text("text")
            })
            .Concat(tail != null ? new[] { tail } : new ColumnSpec[0]).Cast<SheetField>().ToArray()).Note(note);

    private static SheetSpec Questions() =>
        Rows("questions", "questions", Key("id", "question"),
            Text("id").Required(),
            Text("category"),
            Text("label"),
            Text("prompt"),
            Text("answer"),
            Int("fromDay"),
            Text("announce"),
            GateConditions("questionConditions"),
            Rows("questionOverrides", "overrides",
                Text("era").Omit().Ref("eras").Note("the claimed era (blank: any)"),
                List("kinds").Omit().Note("the traveller kinds (RichTourist, PoorTourist, Labourer, Displaced); blank: any"),
                Text("answer")).Note("the answer for some kinds, an era or both (the most specific wins: kinds 2, era 1); every traveller is asked the question's own prompt")).Note("one question per category, asked of every traveller in the same words");

    private static SheetSpec Dialogs() =>
        Rows("dialogs", "dialogs", Key("id", "dialog"),
            Text("id").Required(),
            Text("label").Note("the wheel entry"),
            Bool("repeatable").Omit(),
            GateConditions("dialogConditions"),
            Rows("dialogNodes", "nodes", Key("id", "node"),
                Text("id").Required(),
                Lines("dialogLines"),
                Rows("dialogChoices", "choices", Key("id", "choice"),
                    Text("id").Required(),
                    Text("label"),
                    Lines("choiceLines"),
                    Text("next").Note("the node it leads to (blank: the dialog ends)"),
                    Text("effect")))).Note("narrative dialogs: nodes, their lines and the player's choices");

    private static SheetSpec Premades() =>
        Rows("premades", "premades", Key("id", "premade"),
            Text("id").Required(),
            Text("name"),
            Text("gender"),
            Text("place").Ref("places"),
            Text("truePlace").Ref("places").Note("where they really come from (blank: honest)"),
            Text("birthDate"),
            Text("archetype"),
            Text("intro"),
            Text("recordNote"),
            Text("dialog").Ref("dialogs"),
            Bool("repeatable"),
            Rows("premadeImpacts", "impacts",
                Text("attribute").Ref("contentAttributes"),
                Num("onCorrect"),
                Num("onWrong"),
                Bool("skipNationScore").Omit()),
            Text("kind").Omit().OneOf("RichTourist", "PoorTourist", "Labourer", "Displaced").Note("a 2150 story character's kind (blank: Displaced, the famous)"),
            Text("family").Omit().Ref("countries").Note("a story character's family country: its lineage and generated look (blank: its place's country)"),
            Text("citizenId").Omit().Note("a story character's Citizen ID (000-0000-00), the same at every appearance"),
            Int("debt").Omit().Note("a story character's debt in cr (blank: drawn from its status's range)"),
            Text("employer").Omit().Ref("agencyEmployers").Note("a labourer story character's employer (an agency.employers id of its destination's era; blank: drawn)"),
            Rows("premadePulls", "pulls",
                Text("factor").Ref("worldFactors"),
                Text("outcome").Note("an outcome id of the factor (worldOutcomes)"),
                Num("amount").Note("the pull when accepted, instead of the role's, unscaled")).OmitEmpty().Note("a famous traveller's big pull on the world")).Note("premade characters: real people and written stories");

    private static SheetSpec History() =>
        Single("history", "history",
            Text("lines.leaderGained"),
            Text("lines.leaderLost"),
            Text("lines.carry"),
            Text("lines.dominant").Note("an attribute becomes dominant in a place: {attribute} and {place}"),
            Text("lines.panic").Note("an accepted costume error caused a panic: {place} and {value} (the wrong item)"),
            Text("lines.carryBy").Note("a carry traced to its face: {value}, {place}, {name} (the traveller stamped) and {day}"),
            Text("lines.panicBy").Note("a panic traced to its face: {place}, {value}, {name} and {day}"),
            Text("lines.traced").Note("what a world-outcome headline ends with: the last traveller whose verdict pulled it, {name} and {day}"),
            Rows("historyRules", "rules", Key("id", "rule"),
                Text("id").Required(),
                Text("name"),
                Text("news"),
                Rows("historyConditions", "conditions",
                    Text("type").Required(),
                    Text("key").Omit(),
                    Text("nation").Omit().Ref("countries"),
                    Text("place").Omit().Ref("places"),
                    Text("attribute").Omit().Ref("contentAttributes"),
                    Num("threshold").Omit()),
                Rows("historyEdits", "edits",
                    Text("place").Ref("places"),
                    Text("category"),
                    Text("value")),
                Num("stability").Omit().Note("a change of stability the night the rule fires, a percent of where it stands (-3 takes 3%); blank: none"),
                Text("section").Omit().OneOf("News", "Desk", "Return", "Front").Note("where the line goes: the paper's news (blank), the paper's desk section, nowhere until the character returns (its fired flag, trig:history_{id}:fired), or the front page, leading the news (a famous traveller's homecoming)"),
                Rows("historyPulls", "pulls",
                    Text("factor").Ref("worldFactors"),
                    Text("outcome").Note("an outcome id of the factor (worldOutcomes)"),
                    Num("amount").Note("the pull the night the rule fires")).OmitEmpty().Note("a story beat's pull on the world")).Note("history rules: when their conditions pass at night they rewrite a place's fact; a rule with no edit is a story rule, which prints its news line"));

    /// <summary>The PC block: the steps checklist's sets, the Internet's sites, the Static sites' authored pages, the Lineage Archive's people and relations, and Mail's authored messages.</summary>
    private static SheetSpec Pc() =>
        Single("pc", "pc",
            Rows("pcStepSets", "steps.sets", Key("type", "stepSet"),
                Text("type").Required().OneOf("default", "RichTourist", "PoorTourist", "Labourer", "Displaced").Note("a traveller kind, or default: the steps of a kind with no set of its own"),
                Text("inherit").Omit().Ref("pcStepSets").Note("the set whose steps it starts from; its own step of the same id replaces the parent's (blank: none)"),
                Bool("dataOnly").Omit().Note("true while the kind is not in play yet: its forms and categories may name what a later phase adds"),
                Rows("pcSteps", "steps",
                    Text("id").Required().Note("its label is the UI string steps.{id}"),
                    Text("when").Required().OneOf("PapersReceived", "PaperRead", "Requested", "RulesViewed", "RecordViewed", "Compared", "Asked", "LookedAt")
                        .Note("the check it waits for, never what the check found"),
                    List("categories").Omit().Note("the categories a Compared or Asked step counts (blank: derived from the case)"),
                    Text("statement").Omit().OneOf("Any", "Field", "Answer", "Garment").Note("a Compared step's statement side (blank: any)"),
                    Text("truth").Omit().OneOf("Any", "Reference", "Record", "Paper").Note("a Compared step's truth side (blank: any)"),
                    List("forms").Omit().Note("the form numbers a paper step counts (blank: every paper)"),
                    Text("jump.source").Omit().OneOf("Documents", "Records", "Reference", "Transcript", "Report", "Rules").Note("the tab a click on the step shows"),
                    Text("jump.link").Omit().OneOf("PrimaryName", "FirstUncheckedField", "CostumeClaimed").Note("where a click goes instead of a tab"),
                    Text("hint").Omit().Ref("uiStrings").Note("the UI string of the toast a click shows instead of a jump"),
                    Int("fromDay").Omit().Note("its first day (blank: day 1)")).Note("a set's steps, in order")).Note("the optional steps checklist, one set per traveller kind"),
            Rows("pcSites", "sites", Key("id", "site"),
                Text("id").Required(),
                Text("kind").OneOf("News", "History", "Ancestry", "Static").Note("the page builder that serves it"),
                Text("name"),
                Text("domain").Note("chronet://{domain}: lower-case letters, digits, dots and dashes"),
                Text("glyph").Note("the start-page tile's art key"),
                Text("blurb"),
                Int("fromDay").Note("the first day it is listed")).Note("the Internet's sites"),
            Rows("pcPages", "pages", Key("{site}/{path}", "page"),
                Text("site").Required().Ref("pcSites"),
                Text("path").Note("blank: the site's front page"),
                Text("title"),
                Rows("pcPageBlocks", "blocks",
                    Text("kind").OneOf("Headline", "Heading", "Paragraph", "Note", "Link", "Box"),
                    Text("text"),
                    Text("address").Omit().Note("a Link's site name, domain or chronet:// address"),
                    List("lines").Omit().Note("a Box's lines"))).Note("a Static site's authored pages"),
            Bool("ancestry.includePremades").Note("the premades who are who they claim get cards"),
            Rows("pcPeople", "ancestry.people", Key("id", "person"),
                Text("id").Required(),
                Text("name"),
                Text("born"),
                Text("died"),
                Text("place").Ref("places"),
                Text("note")).Note("the Lineage Archive's people of the past (no traveller's name)"),
            Rows("pcRelations", "ancestry.relations",
                Text("person").Required().Note("a person's or a premade's id: the card it shows on"),
                Text("kind"),
                Text("other").Required().Note("the other card's id")).Note("one direction per row"),
            Rows("pcMail", "mail", Key("id", "mail"),
                Text("id").Required(),
                Int("fromDay").Note("the day it arrives (its date)"),
                Int("untilDay").Note("the last day it is in the inbox; 0 keeps it for the run"),
                Text("flag").Note("a story flag it waits for (blank: none)"),
                Text("from"),
                Text("subject"),
                Values("pcMailBody", "body", Text("text")).Note("its paragraphs")).Note("Mail's authored messages"));

    private static SheetSpec Ui() =>
        Single("ui", "ui",
            Text("readingLanguage"),
            Int("glossPercent"),
            Float("labelMinScale"),
            Float("contrast.text"),
            Float("contrast.largeText"),
            Float("contrast.glyph"),
            Float("contrast.hint"),
            Float("contrast.outline"),
            Float("contrast.minTextFillAlpha"),
            Text("latinFallbackFont"),
            Rows("uiPalette", "paletteMap",
                Text("role"),
                Text("fill"),
                Num("alpha"),
                Text("ink"),
                Text("textClass")),
            Single("uiNeutral", "neutral", new SheetField[] { Text("id") }.Concat(Culture("", "neutral")).ToArray()),
            Rows("uiStrings", "strings", Key("key"),
                Text("key").Required(),
                Text("text"),
                Text("gloss"),
                Text("tier")),
            Rows("uiLanguages", "languages", Key("language", "language"),
                Text("language").Required(),
                Bool("rtl"),
                Rows("uiLanguageEntries", "entries",
                    Text("key").Ref("uiStrings"),
                    Text("text"))));

    /// <summary>Home's house upgrades (the Home upgrades spec HU3): the tree's rows, generated into upgrade and effect assets, and the radio's lines.</summary>
    private static SheetSpec Home() =>
        Single("home", "home",
            Text("radioUpgrade").Note("the house upgrade whose ownership plays a radio line on the sleep panel"),
            Values("homeRadio", "radio", Text("text")).Note("the radio's lines: one a night, in order by the day"),
            Rows("homeUpgrades", "upgrades", Key("id"),
                Text("id").Required().Note("the upgrade's id (saved as owned)"),
                Text("name"),
                Text("category").Required().OneOf("Food", "Housing", "Security", "Health", "Comfort").Note("its column in the House panel"),
                Int("cost").Note("the one-off price in cr"),
                Int("upkeep").Note("cr a night the household pays once it is owned (0: none)"),
                List("requires").Note("the house upgrades it needs owned first (ids of this sheet)"),
                Int("householdExpense").Note("cr a night on rent and utilities (negative saves)"),
                Num("sicknessChance").Note("added to each member's nightly chance to worsen (-0.05 = 5 points less)"),
                Int("careCost").Note("cr on each treatment (negative cheaper)"),
                Int("medicalDrain").Note("cr on each condition point's nightly drain (negative lowers)"),
                Num("mood").Note("the household's mood points (a sick member's nightly recovery chance)"),
                Num("breakInChance").Note("added to the nightly break-in chance (-0.03 = 3 points less)"),
                Num("breakInShare").Note("added to the share of the wallet a break-in takes"),
                Text("blurb").Note("the House panel's line under its name")).Note("the House tree: every effect never takes a knob below 0"),
            Rows("homeBills", "bills", Key("bill"),
                Text("bill").Required().OneOf("Food", "Heating", "Electricity", "Tv", "Medicine").Note("which of the night's bills (one row each)"),
                Text("name").Note("its name on the bills panel"),
                Int("price").Note("cr a night (the Medicine's with the house's careCost)"),
                Text("line").Note("a short line beside it")).Note("the night's optional bills: the Heating and the TV work only with the Electricity paid"),
            Single("homePet", "pet",
                Int("nameMaxLength").Note("the adoption's name limit, in characters"),
                Rows("homePetKinds", "kinds", Key("kind", "kind"),
                    Text("kind").Required().OneOf("Dog", "Cat"),
                    Text("word").Note("the kind in a sentence: {kind}"),
                    Text("suggestedName").Note("the adoption panel's suggestion (a valid name)"),
                    Values("homePetReactions", "reactions", Text("text")).Note("a pat's lines, in turn: {name}"),
                    Values("homePetToyLines", "toyLines", Text("text")).Note("a toy's lines, in turn by the day: {name}, {toy}")),
                Values("homePetHunger", "hunger", Text("text")).Note("hunger in words, best first: {name}"),
                Values("homePetCold", "cold", Text("text")).Note("cold in words, best first"),
                Values("homePetBoredom", "boredom", Text("text")).Note("boredom in words, best first"),
                Values("homePetSickness", "sickness", Text("text")).Note("sickness in words, best first"),
                Text("worse").Note("Home's line after a night it got sicker"),
                Text("better").Note("Home's line after a night it got better"),
                Text("welfareNotice").Note("Home's warning after a night left at the worst"),
                Text("paperAdopted").Note("the paper the morning after the adoption: {name}, {kind}"),
                Text("paperWelfare").Note("the paper after a night left at the worst")).Note("the pet's words: never a number"),
            Rows("homeToys", "toys", Key("id"),
                Text("id").Required().Note("the toy's id (an Orders upgrade, saved as owned)"),
                Text("name"),
                Int("cost").Note("the price in cr at the Orders app"),
                Num("mood").Note("mood points while owned (fewer sick nights, quicker recovery)"),
                Text("blurb").Note("the Orders app's line"))).Note("Home's house upgrades, the radio, the night's bills, the pet and its toys");

    private static SheetSpec Translation() =>
        Single("translation", "translation",
            Int("fromDay"),
            Text("announce"),
            Float("flip.startDelay"),
            Float("flip.letterInterval"),
            Float("flip.letterSeconds"),
            Int("flip.scrambleSteps"),
            List("keyWords.slots").Note("slots whose value stays English in untranslated speech"),
            List("keyWords.words").Note("words that stay English in untranslated speech"),
            Bool("keyWords.digits"),
            Text("fallbackGlyphs"),
            Rows("scripts", "scripts", Key("id", "script"),
                Text("id").Required(),
                Bool("rightToLeft"),
                Fonts("scriptFonts", "fonts")),
            Rows("packs", "packs", Key("id"),
                Text("id").Required(),
                Text("displayName"),
                Int("spokenCost"),
                List("requires").Omit().Note("the upgrade ids the translator's Orders node needs owned first (interview_protocols); blank: none")),
            Rows("tongues", "tongues", Key("id"),
                Text("id").Required(),
                Text("displayName"),
                Text("script").Ref("scripts"),
                Text("pack").Ref("packs"),
                Text("glyphs")));

    // ---- shared shapes ----

    /// <summary>A culture block (a country's "culture" or ui.neutral): the same columns and child sheets under a path prefix.</summary>
    private static SheetField[] Culture(string prefix, string sheetPrefix) => new SheetField[]
    {
        Text(prefix + "displayName"),
        Text(prefix + "language"),
        Bool(prefix + "runtimeFont"),
        Fonts(sheetPrefix + "Fonts", prefix + "fonts"),
        Text(prefix + "headingAdd"),
        Text(prefix + "buttonAdd"),
        Bool(prefix + "stripItalic"),
        Rows(sheetPrefix + "Seeds", prefix + "seeds",
            Text("name"),
            Text("hex")),
        Rows(sheetPrefix + "Overrides", prefix + "overrides",
            Text("role"),
            Text("fill"),
            Text("ink")),
        Rows(sheetPrefix + "Art", prefix + "art",
            Text("name"),
            Text("hex")),
        Text(prefix + "wallpaper"),
    };

    private static SheetSpec Fonts(string name, string path) =>
        Rows(name, path,
            Text("file"),
            Int("face"),
            Text("family"),
            Text("style")).Note("font candidates, tried in order");

    /// <summary>The gate conditions of a question or a dialog (every field written).</summary>
    private static SheetSpec GateConditions(string name) =>
        Rows(name, "conditions",
            Text("type").Required(),
            Text("key"),
            Num("threshold"),
            Text("place").Omit().Ref("places"),
            Text("attribute").Omit().Ref("contentAttributes"),
            Text("nation").Omit().Ref("countries")).Note("all must pass");

    /// <summary>Dialog lines: a node's or a choice's.</summary>
    private static SheetSpec Lines(string name) =>
        Rows(name, "lines",
            Text("id"),
            Text("speaker"),
            Text("expression").Omit(),
            Text("text"));
}
